### ISSUE TITLE
Crashes on white image

### ISSUE THREAD

**Issue by jehaj** [jehaj/thread-art-rust#1]
If you use the algorithm on a white image, then it crashes.

Use a totally white image (e.g. https://singlecolorimage.com/get/ffffff/400x400) and run the algorithm on it.

**Comment by jehaj** [comment]
This problem is solved with d05c6c76496c338b050bd6cf1e9eaa68e65917f1, but the cause of the original problem is not entirely understood yet. The image is 400x400 and grayscale, but still the buffer size is only 20000 instead of 160000 (1/8 of what it is supposed to be). Maybe instead of a byte describing a pixel only a bit is needed. I'm not sure.

The current solution is to just silently exit with an error code of 1. Then the one that calls the algorithm needs to handle the error. Implemented in d05c6c76496c338b050bd6cf1e9eaa68e65917f1.

**Comment by jehaj** [comment]
I am not sure why, but the png library used (https://crates.io/crates/png) automatically limited a picture with only 2 colors (well 1 it was only white, but ImageMagick _identify_ reported 2) reads such a picture as having a bit depth of 1 even though _identify_ reports 8 bit depth.

Using a transformation with expand flag set to true fixed the issue of the wrong buffer size. It still crashes on a white image because of another reason. The flag expands lower than 8 bit depth grayscaled images to 8 bit. See 9a9bbd0c6d36b3e3472257aace4cd62f33880ad1.

**Comment by NikolajK-HTX** [comment]
I'm not going to fix this as an error is shown and the picture is not actually usable for the algorithm and needs to have increased contrast which needs to be handled my something else.

**Comment by jehaj** [comment]
I'm not going to fix this as an error is shown and the picture is not actually usable for the algorithm and needs to have increased contrast which needs to be handled my something else.
